apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Msocial123/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://4C98BFDF0CB66F9E2D5BD11119538446.gr7.us-east-1.eks.amazonaws.com
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
